### ISSUE TITLE
Toy code letters are incorrect

### ISSUE THREAD

**Issue by wizard76** [metafetish/lovesense-js#1]
From the Lovense Cam Model Extension, the correct toy code letters are:
- "a" and "c" are Nora (two different models)
- "b" is Max
- "s" is Lush
- "z" is Hush (their newest toy)

The Chrome extension can be downloaded from http://www.lovense.com/files/lovense_cam.zip but is obfuscated.

Hope this helps!

**Comment by qdot** [comment]
Oops, I'll get that fixed up, thanks!

**Comment by qdot** [comment]
Archiving repo, closing. All new work happening at https://github.com/buttplugio/buttplug-js
