### ISSUE TITLE
Web bluetooth demo

### ISSUE THREAD

**Issue by jnikcmp** [metafetish/lovesense-js#3]
Would it be possible to add a web bluetooth demo for this and maybe update the dependencies? I was not able to compile serialport v4 and virtual-serialport seems to be a private repo or something. Updating the version numbers works (installing wise), but of course the code breaks.

Thanks in advance.

**Comment by qdot** [comment]
Oh, wow, I thought I'd archived this repo, heh.

All development has now moved to the projects at https://buttplug.io. Our github account for that is https://github.com/buttplugio. If you're interested in JS and WebBluetooth, you'll want to check out https://github.com/buttplugio/buttplug-js, which supports all Lovense toys (Plus the Fleshlight Launch and a few others) in WebBluetooth already.
